TimeTracker/Models/CardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TimeTracker.DAL;

namespace TimeTracker.Models
{
    public class CardViewModel
    {
        public Guid CardId { get; set; }
        public string LogComment { get; set; }
        public int Duration { get; set; }
        public DateTime start { get; set; }

        public CardViewModel(WorkCards card)
        {
            this.CardId = card.CardId;
           this.Duration = card.Duration;
           this.LogComment = card.LogComment;
           this.start = card.StartTime;
        }
    }
}

TimeTracker/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTracker.DAL;
using TimeTracker.Models;

namespace TimeTracker.Controllers
{
    public class CardsController : Controller
    {
        //
        // GET: /Cards/

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                List<Tasks> tasks = TasksDAL.GetTasksByUser(User.Identity.Name);
                List<TaskViewModel> tasksViewModel = new List<TaskViewModel>();

                foreach (var task in tasks)
                {
                    tasksViewModel.Add(
                        new TaskViewModel(task)
                    );
                }
                return View(tasksViewModel);
            }
            return RedirectToAction("Index", "Home");
        }

       
        //
        // POST: /Cards/Create

        [HttpPost]
        public ActionResult CreateCard()
        {
            try
            {
                Guid userId = UsersDAL.GetUserByUsername(User.Identity.Name).UserID;
                if (Request.Form["save"] != null)
                {
                    var test = Request.Form["task"];
                    Guid taskId = Guid.Parse(Request.Form["task"]);  
                    CardsDAL.CreateCard(taskId, userId, DateTime.Now, 
                       int.Parse(Request.Form["duration"]), Request.Form["comment"]);
                }
                ViewBag.Success = "Your work card was safed";
                return View();
            }
            catch(Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

    }
}

TimeTracker/Views/Cards/CreateCard.cshtml
@{
    ViewBag.Title = "CreateCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateCard</h2>

@ViewBag.Success

TimeTracker/Views/Cards/Index.cshtml
@using TimeTracker.Models;

@model List<TaskViewModel>

@{
    ViewBag.Title = "WorkCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cards</h2>

<div class="explanation">
You are currently logged as @User.Identity.Name 
Here you have to fill in a form for the task you have worked on and done it.
Once you submit the form, you CANNOT edit it, so please, be sure for tha data you add.
</div>

@ViewBag.Success

<div class="workCard">
@using (Html.BeginForm("CreateCard", "Cards", FormMethod.Post))
{
	<label for="task">Choose your task</label>
	<select id="task" name="task" class="optTasks">
		<option>Choose a task</option>
		@foreach (var task in Model)
        {
            <option value="@task.TaskId">@task.TaskName</option>
        }
	</select>
	<label for="start">StartTime</label>
    <input type="text" id="start" name="start" />
	<label for="duration">Duration</label>
    <input type="text" id="duration" name="duration"/>
	<label for="comment">Short comment</label>
	<textarea id="comment" rows="10" cols="47" name="comment"></textarea>
	<div class="clear"></div>
	<input type="submit" name="save" value="Save card"/>
}
</div>